### ISSUE TITLE
Add change in balance to event UpdatedUserBalance()

### ISSUE THREAD

**Issue by pelsasser** [MARKETProtocol/MARKETProtocol#152]
### User Story
It would be nice for end users to be able to know the change in collateral balances that occur during the event UpdatedUserBalance.

### Why Is this Needed?
*Summary*: Easier tracking in dApp 

### Description
*Type*: Feature!

### Definition of Done
- [ ] add changeInBalance arg to UpdatedUserBalance
- [ ] add tests

**Comment by rojosnow** [comment]
Issue moved to [MARKETProtocol/smartcontracts #1](https://github.com/MARKETProtocol/smartcontracts/issues/1) via [**ZenHub**](https://www.zenhub.com/)

**Comment by mayorcoded** [comment]
Hi @pelsasser ,
I have an interest in solving this issue and I would like to know if anyone is already working on it. I tried to communicate on the #Engineering channel on Discord, but I could not get my phone number verified. I look forward to hearing from you. Mayowa.

**Comment by pelsasser** [comment]
@mayorcoded - that would be great if your willing to tackle this!  Apologies for the slow response and let me know if there is anything you need from me in order to get up to speed.

**Comment by mayorcoded** [comment]
@pelsasser Thanks for your response. First, I would like to share my understanding of the issue and how I intend to approach it so that you can verify before I start to work on the issue.

issue: In the MarketCollateralPool.sol contract file, `changeInBalance` argument needs to be added to the `UpdatedUserBalance` event to reflect the changes in the collateral balances when the event is emitted. 

implementation: 
- add `changeInBalance` paramter to `UpdatedUserBalance` event.
- get collateral balances from `tokenAddressToAccountBalance` mapping.
- in every function where `UpdatedUserBalance` event is emitted, calculate change in balance by doing `changeInBalance =   newBalance - initialBalance`, and add the changeInBalance to the `UpdatedUserBalance` event. Alternatively, (newBalance - initialBalance) can simply be replaced with the amount passed to the function that triggers emit of `UpdatedUserBalance` event.
- emit new `UpdatedUserBalance` event with changeInBalance argument.
- write test for changes made to `UpdatedUserBalance` event

questions: 
- if (newBalance - initialBalance) is used, it may return a negative value, hence, should the type of `changeInBalance` be int to accommodate this?
- are there any details that I might have missed out?

**Comment by pelsasser** [comment]
@mayorcoded 

I think your understanding of the implementation is right on here.  

Your question regarding the negative value and type is a very good and important one.  I commend you on thinking through this prior to coding it!  I believe this value does need to be an `int` type because as you mention it will be signed (+/-).

**Comment by mayorcoded** [comment]
Thanks for the commendation, Phil. I will go ahead and start working on this project, the timeline will be 3 days.

**Comment by mayorcoded** [comment]
Thanks, Phil.

@pelsasser I have a little challenge with the tests. I have implemented the feature - **Add change in balance to event UpdatedUserBalance** - in the contract, and I am working on the tests. There are 4 functions in MarketCollateralPool.sol where the `UpdatedUserBalance` is emitted,  so far, I have written tests for two of them (`depositTokensForTrading` and  `withdrawTokens`). However, I have not been able to test the other two functions (`commitCollateralToPool` and `withdrawCollateralFromPool`) because they are **private** functions, and solidity does not provide a way to test private functions yet. An alternative might be to change the visibility of the functions to public and test them and then change them back to private after testing, but this will defeat the purpose of testing them. 

Do you have any idea about how I can test these functions? Please if you do, kindly share with me. I also noticed that these functions do not have tests in the MarketCollateralPool.js test suite. Were their tests left out for the same reason?

**Comment by perfectmak** [comment]
@mayorcoded Well done. 
Yes, testing private functions is not advisable. 
Here are two possible suggestions to test those events:
1) If you would like to test those you might as well write a test for the public function that uses them i.e. `updatePositions()`, but it would require a little setup before you can successfully call it, set up such as having a correct marketContract and also setting a correct MarketTradingHub address. Then you can call the `updatePositions()` function and listen for the appropriate event.

2) The second one, which might be more straight forward. If you look inside the `MarketCollateralPool.js` tests, we have a bunch of tests that already test `tradeOrder()` and then perform positions check through the `collateralPool.getUserNetPosition.call()` function. You can enhance those tests by also checking if the correct `UpdateUserBalance()` event was broadcasted.

Also, it would be great if you submitted a WIP PR, so we can review and also provide more suggestions.

**Comment by mayorcoded** [comment]
@perfectmak Thanks for the suggestions, I will look into them and also submit a WIP PR.
